### ISSUE TITLE
Create some kind of winning condition per level

### ISSUE THREAD

**Issue by hanneswirnsberger** [LeoTrain/MarioIsaac#12]
How do we indicate when a Level is sucessfully finished? Who is handling this? -> something bigger than level?

**Comment by LeoTrain** [comment]
> How do we indicate when a Level is sucessfully finished? Who is handling this? -> something bigger than level?

At the moment we don't, we just go back to the main menu when the player is dead without reseting the level.

**Comment by hanneswirnsberger** [comment]
Okok, lets do it in a nacht und nebel action :)

**Comment by LeoTrain** [comment]
Nebel und nacht action done ;)
