### ISSUE TITLE
> to think about :)

### ISSUE THREAD

**Issue by hanneswirnsberger** [LeoTrain/MarioIsaac#6]
> 

Great work! Let's use custom events more often as i assume that we can achieve great things with it, without loosing any readability :) 

Maybe we should also think about adding a own file to gather all ideas or ToDos 

_Ursprünglich gepostet von @hanneswirnsberger in https://github.com/LeoTrain/MarioIsaac/pull/4#issuecomment-2357821434_

**Comment by LeoTrain** [comment]
Mhhh, I see, I see... You mean like a todo.txt and ideas.txt ? I'll make them and push them on the main branch. Or is it better to do it in the Dev branch ?

**Comment by LeoTrain** [comment]
Actually, if you go to our Project page we can put the tasks/ideas into the roadmap. What do you think about it ?

**Comment by LeoTrain** [comment]
or should we keep it open to talk about stuff in here

**Comment by hanneswirnsberger** [comment]
I would close it and we could just create new ones if needed
