### ISSUE TITLE
Changes for game.py

### ISSUE THREAD

**Issue by LeoTrain** [LeoTrain/MarioIsaac#8]
- Split up handle_events
- Create a dictionary for the run method

I saw that we handle_input in main_menu. Maybe we could do the same for player enemies, etc...

**Comment by hanneswirnsberger** [comment]
> - Split up handle_events
> - Create a dictionary for the run method
> 
> I saw that we handle_input in main_menu. Maybe we could do the same for player enemies, etc...

 Create a dictionary for the run method -> you mean something like event_dick?

**Comment by LeoTrain** [comment]
I think you mean making the run method event based, that's not a bad idea. But I thought about making a small dictionary to make the run method cleaner.

**Comment by hanneswirnsberger** [comment]
Like event dick right? Need to check it, lets discuss later

**Comment by LeoTrain** [comment]
Yes a dictionary halt wie event_dick

**Comment by hanneswirnsberger** [comment]
Top👍
